parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Systemeio\TestForCandidates\PaymentProcessor\PaypalPaymentProcessor: ~
    Systemeio\TestForCandidates\PaymentProcessor\StripePaymentProcessor: ~